-- Populate `department` table
INSERT INTO department (dep_id, dep_name)
VALUES
    (1, 'Cardiology'),
    (2, 'Neurology'),
    (3, 'Orthopedics'),
    (4, 'Pediatrics'),
    (5, 'Oncology'),
    (6, 'Gastroenterology'),
    (7, 'Ophthalmology'),
    (8, 'Urology'),
    (9, 'Dermatology'),
    (10, 'Endocrinology'),
    (11, 'Pulmonology'),
    (12, 'Rheumatology'),
    (13, 'Hematology'),
    (14, 'Nephrology'),
    (15, 'Geriatrics'),
    (16, 'Infectious Diseases'),
    (17, 'Psychiatry'),
    (18, 'Allergy and Immunology'),
    (19, 'Emergency Medicine'),
    (20, 'Anesthesiology'),
    (21, 'Radiology'),
    (22, 'Pathology'),
    (23, 'Otolaryngology'),
    (24, 'Neonatology'),
    (25, 'Physical Therapy'),
    (26, 'Occupational Therapy'),
    (27, 'Speech Therapy'),
    (28, 'Cardiothoracic Surgery'),
    (29, 'Plastic Surgery'),
    (30, 'Orthodontics'),
    (31, 'Periodontics'),
    (32, 'Pediatric Dentistry'),
    (33, 'Oral and Maxillofacial Surgery'),
    (34, 'Obstetrics and Gynecology'),
    (35, 'Family Medicine'),
    (36, 'Internal Medicine'),
    (37, 'Neurosurgery'),
    (38, 'Vascular Surgery'),
    (39, 'Podiatry'),
    (40, 'Dietetics'),
    (41, 'Clinical Psychology'),
    (42, 'Social Work'),
    (43, 'Chiropractic'),
    (44, 'Optometry'),
    (45, 'Pharmacy'),
    (46, 'Nursing'),
    (47, 'Medical Records'),
    (48, 'Health Administration'),
    (49, 'Biomedical Engineering'),
    (50, 'Medical Research');
