-- Populate `pharmacy` table
INSERT INTO pharmacy (med_id, med_name, med_manufacturer, abbreviated_usage)
VALUES
    (1, 'Paracetamol', 'Indian Pharmaceuticals Ltd.', 'Pain relief'),
    (2, 'Amoxicillin', 'Dr. Reddy''s Laboratories', 'Antibiotic'),
    (3, 'Omeprazole', 'Sun Pharmaceuticals', 'Acid reflux'),
    (4, 'Atorvastatin', 'Cipla Ltd.', 'Cholesterol management'),
    (5, 'Metformin', 'Cadila Healthcare', 'Diabetes management'),
    (6, 'Aspirin', 'Torrent Pharmaceuticals Ltd.', 'Blood thinner'),
    (7, 'Ibuprofen', 'Alembic Pharmaceuticals Ltd.', 'Anti-inflammatory'),
    (8, 'Ranitidine', 'Mankind Pharma Ltd.', 'Ulcer treatment'),
    (9, 'Ciprofloxacin', 'Glenmark Pharmaceuticals', 'Antibiotic'),
    (10, 'Simvastatin', 'Aurobindo Pharma Ltd.', 'Cholesterol management'),
    (11, 'Metoprolol', 'Lupin Ltd.', 'Blood pressure management'),
    (12, 'Levothyroxine', 'Biocon Ltd.', 'Thyroid disorder'),
    (13, 'Clopidogrel', 'Wockhardt Ltd.', 'Blood thinner'),
    (14, 'Lisinopril', 'Abbott India Ltd.', 'Blood pressure management'),
    (15, 'Warfarin', 'Ipca Laboratories Ltd.', 'Blood thinner'),
    (16, 'Gabapentin', 'Alkem Laboratories Ltd.', 'Neuropathic pain'),
    (17, 'Tramadol', 'Zydus Cadila', 'Pain relief'),
    (18, 'Diazepam', 'Glenmark Pharmaceuticals Ltd.', 'Anxiety disorder'),
    (19, 'Sertraline', 'Sun Pharmaceuticals Industries Ltd.', 'Depression'),
    (20, 'Escitalopram', 'Dr. Reddy''s Laboratories', 'Antidepressant'),
    (21, 'Amlodipine', 'Torrent Pharmaceuticals Ltd.', 'Blood pressure management'),
    (22, 'Venlafaxine', 'Lupin Ltd.', 'Depression'),
    (23, 'Clarithromycin', 'Macleods Pharmaceuticals Ltd.', 'Antibiotic'),
    (24, 'Fluoxetine', 'Cipla Ltd.', 'Depression'),
    (25, 'Metronidazole', 'Intas Pharmaceuticals Ltd.', 'Antibiotic'),
    (26, 'Prednisolone', 'Alembic Pharmaceuticals Ltd.', 'Anti-inflammatory'),
    (27, 'Furosemide', 'Sun Pharmaceuticals', 'Diuretic'),
    (28, 'Cephalexin', 'Glenmark Pharmaceuticals', 'Antibiotic'),
    (29, 'Methotrexate', 'Wockhardt Ltd.', 'Rheumatoid arthritis'),
    (30, 'Bisoprolol', 'Ipca Laboratories Ltd.', 'Blood pressure management');
